name: NPM Publish
on: 
    workflow_dispatch:
      inputs:
        tag:
          description: 'Pre-release tag'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Drop 'v' prefix from tag
        id: version
        env:
          VERSION: ${{inputs.tag}}
        run: echo "number='${NEXT##*v}'" >> $GITHUB_OUTPUT

      - name: Download Release ${{inputs.tag}}
        uses: robinraju/release-downloader@v1
        id: download
        with:
          tag: ${{inputs.tag}}
          fileName: up-yeah-${{steps.version.outputs.number}}.tgz
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: chmod +x scripts/build-install.sh
      - run: ./scripts/build-install.sh
      - run: npm publish --provenance --access public ${{steps.download.outputs.downloaded_files[0]}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
      
      - name: Update Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{inputs.tag}}
          allowUpdates: true
          draft: false
          prerelease: false
          makeLatest: false
          generateReleaseNotes: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{github.token}}

      

          
