name: NPM Publish
on: 
    workflow_dispatch:
      inputs:
        tag:
          description: 'git commit sha'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download Release ${{inputs.tag}}
        uses: robinraju/release-downloader@v1
        id: download
        with:
          tag: ${{inputs.tag}}
          fileName: up-yeah-${{inputs.tag}}.tgz
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: chmod +x scripts/build-install.sh
      - run: ./scripts/build-install.sh
      - run: npm publish --provenance --access public ${{steps.download.outputs.downloaded_files[0]}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
