name: NPM Publish
on: 
    workflow_dispatch:
      inputs:
        tag:
          description: 'release tag'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download up-yeah${{inputs.tag}}
        id: download
        uses: actions/download-artifact@v4
        with: 
          name: up-yeah@${{inputs.tag}}.tgz

      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: chmod +x scripts/build-install.sh
      - run: ./scripts/build-install.sh
      - run: npm publish --provenance --access public ${{steps.download.outputs.download-path}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
