name: Build and Release
on:
  workflow_run:
    workflows: [ Test ]
    branches:
      - master
      - 'ci/**'
    types:
      - completed


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{github.token}}
          branch: master
          noVersionBumpBehavior: current
          majorList: "release"
          
      

      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: NPM Version Bump
        if:  ${{ !contains(steps.semver.outputs.bump, 'none' )}}
        id: version-bump
        run: npm version ${{steps.semver.outputs.bump}}

      - name: Make Filename
        id: split
        env:
          NEXT: ${{steps.semver.outputs.bump}}
        run: echo echo "::set-output name=package-name::up-yeah-${NEXT##*v}.tgz"

    
      - run: chmod +x scripts/build-install.sh
      - run: ./scripts/build-install.sh

   
      - name: Zip artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r up-yeah@${{steps.semver.outputs.next}}.zip lib

      - name: List artifacts
        run: |
          ls -lr

      
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{steps.semver.outputs.next}}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "up-yeah@${{steps.semver.outputs.next}}.zip"
          draft: false
          makeLatest: true
          name: ${{steps.semver.outputs.next}}
          token: ${{github.token}}

        
      - name: NPM Publish
        uses: actions/setup-node@v4
        if:  ${{ !contains(steps.semver.outputs.bump, 'none' )}}
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd lib
      - run: npm pack
      - run: npm publish --provenance --access public ${{steps.split.outputs.package-name}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
