name: Build and Release
on:
  workflow_run:
    workflows: [Testing]
    branches: [master]


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{github.token}}
          branch: main
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "lib/"
          draft: false
          makeLatest: true
          name: ${{steps.semver.outputs.next}}
          body: "Changelog"
          token: ${{github.token}}