name: Build and Release
on:
  workflow_run:
    workflows: [ Test ]
    branches: [ master, ci/* ]
    types:
      - completed


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node version 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{github.token}}
          branch: master
          noVersionBumpBehavior: current
      - name: Zip artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r up-yeah@${{steps.semver.outputs.next}}.zip lib

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: up-yeah@${{steps.semver.outputs.next}}.zip
          path: up-yeah@${{steps.semver.outputs.next}}.zip

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{steps.semver.outputs.next}}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "up-yeah@${{steps.semver.outputs.next}}"
          draft: false
          makeLatest: true
          name: ${{steps.semver.outputs.next}}
          body: "Changelog"
          token: ${{github.token}}
