name: Build and Release
on: workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: chmod +x scripts/build-install.sh
      - run: ./scripts/build-install.sh

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{github.token}}
          branch: master
          noVersionBumpBehavior: current
      - name: Zip artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r up-yeah@${{steps.semver.outputs.next}}.zip lib

      - name: List artifacts
        run: |
          ls -lr

      - name: Make Release Tarball
        id: release-tarball
        run: cd lib && npm pack  

      - name: List artifacts lib
        run: |
          cd lib && ls -lr 

      - name: Tag Local
        run: git tag ${{steps.semver.outputs.next}} -f
      - name: Force push tag
        run: git push -f --tags

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{steps.semver.outputs.next}}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "up-yeah@${{steps.semver.outputs.next}}.zip, lib/up-yeah-${{steps.semver.outputs.nextStrict}}.tgz"
          draft: true
          generateReleaseNotes: true
          omitPrereleaseDuringUpdate: true
          omitNameDuringUpdate: true
          name: ${{steps.semver.outputs.next}}
          token: ${{github.token}}
