name: Up Yeah Actions
strategy:
  matrix:
    node-version: ['16.x', '18.x', '20.x']

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version ${{matrix.node-version}}
      - run: yarn install --frozen-lockfile
      - run: yarn test
